version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-service
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    restart: unless-stopped
    command: ["npm", "run", "dev"]
